export const LAY_DANH_SACH_PHIM = "LAY_DANH_SACH_PHIM";
export const LAY_DANH_SACH_BANNER_PHIM = "LAY_DANH_SACH_BANNER_PHIM";
export const CHI_TIET_PHIM = "CHI_TIET_PHIM";
export const BAT_DAU_LAY_DU_LIEU = "BAT_DAU_LAY_DU_LIEU";
