const LAY_ThONG_TIN_LICH_CHIEU = "LAY_ThONG_TIN_LICH_CHIEU";
const START_LOADING_DATA = "START_LOADING_DATA";
const LOADING_DATA_ERROR = "LOADING_DATA_ERROR";
const LAY_THONG_TIN_HE_THONG_RAP = "LAY_THONG_TIN_HE_THONG_RAP";
const LAY_THONG_TIN_CUM_RAP_THEO_HE_THONG =
  "LAY_THONG_TIN_CUM_RAP_THEO_HE_THONG";

export {
  LAY_ThONG_TIN_LICH_CHIEU,
  START_LOADING_DATA,
  LOADING_DATA_ERROR,
  LAY_THONG_TIN_HE_THONG_RAP,
  LAY_THONG_TIN_CUM_RAP_THEO_HE_THONG,
};
