const LAY_ThONG_TIN_LICH_CHIEU = "LAY_ThONG_TIN_LICH_CHIEU";
const START_LOADING_DATA = "START_LOADING_DATA";
const LOADING_DATA_ERROR = "LOADING_DATA_ERROR";
export { LAY_ThONG_TIN_LICH_CHIEU, START_LOADING_DATA, LOADING_DATA_ERROR };
