export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG';
export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const DANG_KY_ACTION = 'DANG_KY_ACTION';
export const THONG_TIN_TAI_KHOAN = 'THONG_TIN_TAI_KHOAN'
export const LOAI_NGUOI_DUNG = 'LOAI_NGUOI_DUNG'
export const THEM_NGUOI_DUNG = 'THEM_NGUOI_DUNG'
