const GET_ALL_USER = "GET_ALL_USER";
const DANG_KY = "DANG_KY";
const DANG_NHAP = "DANG_NHAP";
const DANG_XUAT = "DANG_XUAT";
const GUI_THONG_BAO = "GUI_THONG_BAO";
export { GET_ALL_USER, DANG_KY, DANG_NHAP, DANG_XUAT, GUI_THONG_BAO };
